openapi: 3.0.0
info:
  title: Innobyte User Authentication API
  version: 1.0.0
  description: API for user authentication and management
servers:
  - url: http://localhost:3000
tags:
  - name: Auth
    description: Authentication operations
  - name: User
    description: User-related operations

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: User ID
        name:
          type: string
          description: User name
        email:
          type: string
          format: email
          description: User email
      required:
        - name
        - email

    UserSignInDto:
      type: object
      properties:
        email:
          type: string
          format: email
          description: User email
        password:
          type: string
          format: password
          description: User password
      required:
        - email
        - password

    UserSignupDto:
      type: object
      properties:
        name:
          type: string
          description: User name
        email:
          type: string
          format: email
          description: User email
        password:
          type: string
          format: password
          description: User password
      required:
        - name
        - email
        - password

    VerifyOtpDto:
      type: object
      properties:
        userId:
          type: string
          description: User ID
        otp:
          type: string
          description: OTP code
      required:
        - userId
        - otp

    ResendOtpDto:
      type: object
      properties:
        userId:
          type: string
          description: User ID
      required:
        - userId

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Response message
        data:
          oneOf:
            - $ref: "#/components/schemas/User"
            - type: object
              properties:
                user:
                  $ref: "#/components/schemas/User"
                accessToken:
                  type: string
                  description: JWT access token

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/login:
    post:
      tags:
        - Auth
      summary: Sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignInDto"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/signup:
    post:
      tags:
        - Auth
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignupDto"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/profile:
    get:
      tags:
        - User
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/verify-otp:
    post:
      tags:
        - Auth
      summary: Verify the OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyOtpDto"
      responses:
        "200":
          description: OTP verified successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid OTP or bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/resend-otp:
    post:
      tags:
        - Auth
      summary: Resend OTP to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResendOtpDto"
      responses:
        "200":
          description: OTP resent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Bad request or user already verified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
